-- MySQL Script generated by MySQL Workbench
-- Sat Jun 22 03:03:29 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tia_lili
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `tia_lili` ;

-- -----------------------------------------------------
-- Schema tia_lili
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tia_lili` DEFAULT CHARACTER SET utf8 ;
USE `tia_lili` ;

-- -----------------------------------------------------
-- Table `tia_lili`.`Bebidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`Bebidas` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`Bebidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor` DECIMAL NOT NULL,
  `disponivel` TINYINT NULL DEFAULT 1,
  `img` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`tipo_carnes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`tipo_carnes` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`tipo_carnes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `valor_p` DECIMAL NOT NULL,
  `valor_g` DECIMAL NOT NULL,
  `img` VARCHAR(100) NULL,
  `disponivel` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`acompanhamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`acompanhamentos` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`acompanhamentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `disponivel` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`marmitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`marmitas` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`marmitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_carnes_id1` INT NOT NULL,
  `tamanho` INT NOT NULL,
  `obs` VARCHAR(200) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marmita_tipo_carnes_idx` (`tipo_carnes_id1` ASC) VISIBLE,
  CONSTRAINT `fk_marmita_tipo_carnes`
    FOREIGN KEY (`tipo_carnes_id1`)
    REFERENCES `tia_lili`.`tipo_carnes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`Usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`Usuarios` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`Usuarios` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `cep` INT NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`pedidos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `total` DECIMAL(2) NULL DEFAULT 0,
  `status` VARCHAR(15) NULL DEFAULT 'carrinho',
  `pagamento` VARCHAR(15) NULL DEFAULT 'pix',
  `entrega` VARCHAR(15) NULL DEFAULT 'entrega',
  `taxa_entrega` DECIMAL(2) NULL DEFAULT 0,
  `Usuarios_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `tia_lili`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`marmita_acompanhamentos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`marmita_acompanhamentos` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`marmita_acompanhamentos` (
  `marmita_id1` INT NOT NULL,
  `acompanhamentos_id` INT NOT NULL,
  INDEX `fk_marmita_acompanhamentos_marmita1_idx` (`marmita_id1` ASC) VISIBLE,
  INDEX `fk_marmita_acompanhamentos_acompanhamentos1_idx` (`acompanhamentos_id` ASC) VISIBLE,
  PRIMARY KEY (`marmita_id1`, `acompanhamentos_id`),
  CONSTRAINT `fk_marmita_acompanhamentos_marmita1`
    FOREIGN KEY (`marmita_id1`)
    REFERENCES `tia_lili`.`marmitas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_marmita_acompanhamentos_acompanhamentos1`
    FOREIGN KEY (`acompanhamentos_id`)
    REFERENCES `tia_lili`.`acompanhamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`pedido_marmitas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`pedido_marmitas` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`pedido_marmitas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedidos_id` INT NOT NULL,
  `marmita_id` INT NOT NULL,
  INDEX `fk_pedido_marmitas_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  INDEX `fk_pedido_marmitas_marmita1_idx` (`marmita_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_marmitas_pedidos1`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `tia_lili`.`pedidos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_marmitas_marmita1`
    FOREIGN KEY (`marmita_id`)
    REFERENCES `tia_lili`.`marmitas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`pedido_bebidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`pedido_bebidas` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`pedido_bebidas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pedidos_id` INT NOT NULL,
  `Bebidas_id` INT NOT NULL,
  INDEX `fk_pedido_marmitas_pedidos1_idx` (`pedidos_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  INDEX `fk_pedido_bebidas_Bebidas1_idx` (`Bebidas_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_marmitas_pedidos10`
    FOREIGN KEY (`pedidos_id`)
    REFERENCES `tia_lili`.`pedidos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_bebidas_Bebidas1`
    FOREIGN KEY (`Bebidas_id`)
    REFERENCES `tia_lili`.`Bebidas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`Usuarios_adm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`Usuarios_adm` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`Usuarios_adm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `cargo` VARCHAR(20) NOT NULL,
  `email` VARCHAR(75) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tia_lili`.`restaurantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `tia_lili`.`restaurantes` ;

CREATE TABLE IF NOT EXISTS `tia_lili`.`restaurantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
